### ISSUE TITLE
Making a new release

### ISSUE THREAD

**Issue by adamjohnwright** [BioPAX/validator#29]
I made a ticket that was resolved a while ago to make it so this codebase works with Java 11. That work was done. I am wondering if a release could be made so that I could point to the new version from my Pom file without creating it locally.

**Comment by IgorRodchenkov** [comment]
Hi Adam,I think snapshots are periodically deployed to OSSRH public repo, but not “officially released” (I freelance on BioPAX/PC projects to maintain/improve). It’s not in Central Maven yet.Let me see if making some release would be possible soon. Which version are you building/using now, branch?I’m mainly working on the new v6, java >16, which will use updated paxtools and  bioregistry.io instead of Miriam to validate/normalize e.g.  xrefs, etc.  Hope to release (and run at www.biopax.org/validator) this year.Best regards,Igor R.On Aug 3, 2023, at 2:46 PM, Adam Wright ***@***.***> wrote:﻿
I made a ticket that was resolved a while ago to make it so this codebase works with Java 11. That work was done. I am wondering if a release could be made so that I could point to the new version from my Pom file without creating it locally.

**Comment by IgorRodchenkov** [comment]
in meantime, use  add this repo to your pom.xml
<repositories>
        <repository>
            <id>ossrh</id>
            <name>OSSRH Repository</name>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
    </repositories>

**Comment by IgorRodchenkov** [comment]
@adamjohnwright, @gbader, @emekdemir  
- just released BioPAX Validator v5.1.0 (also paxtools 5.2.1 and 5.3.0) to Maven Central; updated the site/docs on Github too. 
The web app at www.biopax.org/validator is not updated yet (better skip and update with v6.0.0 once ready - to use bioregistry.io for validation/norm.)

**Comment by adamjohnwright** [comment]
Hi, sorry for taking so long to respond. It was a long weekend in Ontario. Thanks so much for making a release. I hope to get to this within the next release or two. I did some testing with this code a while ago by making the jar locally a couple of months or more ago. I was successful but it is still at the stage where I need to do more testing to deploy it. I will add this to our to-do list.

**Comment by IgorRodchenkov** [comment]
see also bug #33
