### ISSUE TITLE
Validating multiple files via biopax-validator-client.jar 

### ISSUE THREAD

**Issue by quirinmanz** [BioPAX/validator#33]
Hello,

Thank you for the useful suite.

I am trying to validate a directory with multiple small owl files via the client. Unfortunately, only on file is included in the HTML report. The docs say: 
```
Available parameters: 
<path> <output> [xml|html|biopax] [auto-fix] [only-errors] [maxerrors=n] [notstrict]
        - validate a BioPAX file/directory (up to ~25MB in total size, -
        otherwise, please use the biopax-validator.jar instead)
        in the directory using the online BioPAX Validator service
        (generates html or xml report, or gets the processed biopax
        (cannot fix all errros though) see http://www.biopax.org/validator)
```

Do I have to run it multiple times, or might there be a problem with sending the files/fetching the reports?

Best,

Quirin

**Comment by IgorRodchenkov** [comment]
Hi Quirin,Please attach the command you used and logs (also JDK/Java version), and where did you get the biopax validator client jar.It’s also possible that those missing results files were malformed biopax data… Have you tried to check with the online biopax validator first?Igor.On Feb 1, 2024, at 11:16, Quirin Manz ***@***.***> wrote:﻿
Hello,
Thank you for the useful suite.
I am trying to validate a directory with multiple small owl files via the client. Unfortunately, only on file is included in the HTML report. The docs say:
Available parameters: 
<path> <output> [xml|html|biopax] [auto-fix] [only-errors] [maxerrors=n] [notstrict]
        - validate a BioPAX file/directory (up to ~25MB in total size, -
        otherwise, please use the biopax-validator.jar instead)
        in the directory using the online BioPAX Validator service
        (generates html or xml report, or gets the processed biopax
        (cannot fix all errros though) see http://www.biopax.org/validator)

Do I have to run it multiple times, or might there be a problem with sending the files/fetching the reports?
Best,
Quirin

**Comment by IgorRodchenkov** [comment]
I think it's a bug... Will debug.

**Comment by IgorRodchenkov** [comment]
In mean times, please use local validator instead of online/client. Download and unzip the validator all-in-one zip here https://sourceforge.net/projects/biopax/files//validator/ or here https://repo.maven.apache.org/maven2/org/biopax/validator/distr/5.1.0/distr-5.1.0-all.zip, and run e.g. `sh validate.sh yourDataDir --profile=notstrict` (run w/o args for options) from that dir, or better from inside the data dir using full path to the validate.sh. It will write the output files in the current dir.

**Comment by quirinmanz** [comment]
Hi Igor,
I am now using the local validator, but my files are quite small, and the OBO parsing in the local version takes some time, so using the server would be nice.
Currently, I am getting an Internal Server Error 500 via the web interface and the Java client (which makes sense).
I am using:
`/input_data# java -jar /biopax-validator/biopax-validator-client.jar . client_validator.html notstrict`
with
`openjdk 20.0.2.1 2023-08-22`
and downloaded the zip for 5.1 from Sourceforge.
Not sure where the logs are, but I am happy to provide more information.
Best,
Quirin

**Comment by IgorRodchenkov** [comment]
@quirinmanz which data file triggers "Internal Server Error 500", or any?
I just checked with biopax.org/validator - no errors, it works fine for my example files...

Logs are printed in the terminal when you run the java command...
You cn redirect all logs to a file by adding `2>&1 >validator-log.txt` to the end of the command.

Did you place your data and biopax-validator files under root folder "/", and run as root (usually path is like /home/username/...)?

PS:
local Validator takes time to start/init due to parsing OBO ontologies every time... In the next version, v6, I will fix the local cache bug, and validator with run much faster on the 2nd and next runs at least...

Anyway, I can try to fix this bug and also replace/upgrade the online validator with new v6.0.0 (will use bioregistry.io instead of identifiers.org/Miriam data for CVs, xrefs validation) soon.

**Comment by IgorRodchenkov** [comment]
@quirinmanz  Thank you for reporting the bug, nice catch!
It was the vlidator client bug only; the web app is fine for now.
I uploaded the latest SNAPSHOTs to the public [snapshots OSSRH m2 repo](https://oss.sonatype.org/content/repositories/snapshots/org/biopax/validator/) and Sourceforge as well; so please wry using https://sourceforge.net/projects/biopax/files/validator/biopax-validator-client-6.0.0-SNAPSHOT-jar-with-dependencies.jar/download JAR (or use the LATEST from  https://oss.sonatype.org/content/repositories/snapshots/org/biopax/validator/biopax-validator-client/6.0.0-SNAPSHOT/) 

I tried and it worked for me both when connecting to current online biopax.org/validator/check (default, v.5.1.0 i think) or local web app (the fixed client works for both v5 and v6 validator app)

**Comment by quirinmanz** [comment]
@IgorRodchenkov Thank you for your help! It works wonderfully :)
